version: "3.4"

services: 
  database:
    image: mongo:4.2.16
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rahasia
      MONGO_INITDB_DATABASE: test
  app:
    image: server
    restart: always
    ports: 
      - '8080:8080'
    environment: 
      DB_URI: mongodb://mongo:27017/
      DB_NAME: test
      DB_COLLECTION_NAME: todolist
    